const MOCK = {
  meeting:{title:'Развитие химической промышленности и техника безопасности',date:'23 сентября 2026',duration_seconds:274.25,language:'Русский · ru',participants:['SPEAKER_01','SPEAKER_02']},
  summary:{executive_summary:'Совещание охватило развитие химической промышленности и технику безопасности. Зафиксированы поручения по закупу сырья, финансированию модернизации, аудиту датчиков и работе с подрядчиками.',key_topics:['Химическая промышленность','Инвестиционные проекты','Техника безопасности','Подрядчики'],decisions:['Разработать единую стратегию закупа сырья.','Провести аудит датчиков и СИЗ на всех площадках.','Синхронизировать бюджет безопасности с инвестпланом.']},
  action_items:[
    {id:'a1',task:'Разработать единую стратегию закупа сырья для химических активов группы',assignee:'Гульмира Сериковна',deadline:'15 октября',speaker:'SPEAKER_01',timestamp_start:79,timestamp_end:88,source_quote:'Разработать единую стратегию закупа сырья для химических активов группы, ответственный Гульмира Сериковна, срок до 15 октября.',confidence:.92},
    {id:'a2',task:'Провести совещание с проектным институтом и зафиксировать график поставки катализаторов',assignee:'Айнур Каировна',deadline:'26 сентября',speaker:'SPEAKER_01',timestamp_start:89,timestamp_end:99,source_quote:'Провести совещание с проектным институтом и зафиксировать график поставки катализаторов.',confidence:.87},
    {id:'a3',task:'Подготовить финансовое решение по проекту модернизации завода',assignee:'Тимур Балатович',deadline:'30 сентября',speaker:'SPEAKER_01',timestamp_start:99,timestamp_end:110,source_quote:'Подготовить финансовое решение по проекту модернизации завода, ответственный Тимур Балатович, срок до 30 сентября.',confidence:.9},
    {id:'a4',task:'Провести юридическую проверку штрафных санкций по контракту',assignee:'Юридический департамент',deadline:'30 сентября',speaker:'SPEAKER_01',timestamp_start:111,timestamp_end:118,source_quote:'Провести юридическую проверку штрафных санкций по контракту.',confidence:.81},
    {id:'a5',task:'Провести полный аудит датчиков утечки и средств индивидуальной защиты на 11 площадках',assignee:'Нурлан Сагатович',deadline:'15 октября',speaker:'SPEAKER_01',timestamp_start:185,timestamp_end:201,source_quote:'Мне нужен полный аудит по всем датчикам утечки и средствам индивидуальной защиты на всех одиннадцати площадках.',confidence:.84},
    {id:'a6',task:'Провести внеплановый инструктаж по газоопасным работам на всех площадках',assignee:'Нурлан Сагатович',deadline:'Следующая неделя',speaker:'SPEAKER_01',timestamp_start:231,timestamp_end:245,source_quote:'На следующей неделе — внеплановый инструктаж на всех площадках, особенно там, где газоопасные работы.',confidence:.91}
  ],
  transcript:[
    {speaker:'SPEAKER_01',start:0,end:14.9,text:'Коллеги, начинаем. На повестке один вопрос — состояние и перспективы развития химической отрасли в рамках группы.'},
    {speaker:'SPEAKER_02',start:15.3,end:39.6,text:'По итогам девяти месяцев загрузка мощностей держится на уровне 71%. Основная проблема — устаревшее оборудование и отсутствие единой стратегии закупа сырья.'},
    {speaker:'SPEAKER_01',start:46,end:59,text:'По проекту модернизации завода техническое обоснование готово на 60%. Нужно решение по финансированию до конца квартала.'},
    {speaker:'SPEAKER_02',start:64,end:76,text:'Предлагаю провести совместное совещание с институтом до конца недели и зафиксировать финальный график поставок.'},
    {speaker:'SPEAKER_01',start:79,end:88,text:'Разработать единую стратегию закупа сырья для химических активов группы, ответственный Гульмира Сериковна, срок до 15 октября.'},
    {speaker:'SPEAKER_01',start:111,end:118,text:'Провести юридическую проверку штрафных санкций по контракту, срок до 30 сентября.'},
    {speaker:'SPEAKER_02',start:170,end:182,text:'По технике безопасности был инцидент: датчики утечки газа не проходили поверку с прошлого года.'},
    {speaker:'SPEAKER_01',start:185,end:201,text:'Мне нужен полный аудит по всем датчикам утечки и средствам индивидуальной защиты на всех одиннадцати площадках. К пятнадцатому октября жду отчёт.'},
    {speaker:'SPEAKER_01',start:231,end:245,text:'На следующей неделе — внеплановый инструктаж на всех площадках, особенно там, где газоопасные работы.'},
    {speaker:'SPEAKER_02',start:258,end:273,text:'Итого жду от каждого отчёт по поручениям. На этом по безопасности всё, коллеги, спасибо.'}
  ]
};

const $=id=>document.getElementById(id); const clone=x=>JSON.parse(JSON.stringify(x));
let state={data:clone(MOCK),audioUrl:null,fileName:'Sample meeting · local demo'};
const fmtTime=s=>{s=Math.max(0,Number(s)||0);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const API_BASE='http://127.0.0.1:8000';
function normalize(raw){if(!raw||typeof raw!=='object')throw new Error('Backend returned an empty response');if(!raw.meeting||!raw.summary||!Array.isArray(raw.action_items)||!Array.isArray(raw.transcript))throw new Error('Backend returned malformed meeting JSON');return raw}
function setProcessingStage(stage){document.querySelectorAll('.stage').forEach(x=>{const done=['upload','stt','tasks','protocol'].indexOf(x.dataset.stage)<['upload','stt','tasks','protocol'].indexOf(stage);x.classList.toggle('active',x.dataset.stage===stage);x.classList.toggle('done',done);const s=x.querySelector('span');if(s)s.textContent=x.classList.contains('done')?'✓':x.classList.contains('active')?'●':'○'});$('processingHint').textContent='Обработка аудиозаписи может занять несколько минут.'}
function showProcessingError(message){$('processingHint').textContent=message;$('processingHint').style.color='#a23b3b';setProcessingStage('stt')}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
async function processMeeting(file){if(!file)throw new Error('Choose an audio file to process');state.fileName=file.name;state.audioUrl=URL.createObjectURL(file);setProcessingStage('stt');const form=new FormData();form.append('audio',file,file.name);let response;try{response=await fetch(`${API_BASE}/api/meetings/process?async=true`,{method:'POST',body:form})}catch(error){throw new Error('Backend unavailable. Make sure the API is running on 127.0.0.1:8000.')}if(!response.ok){let detail='Upload failed';try{detail=(await response.json()).detail||detail}catch{}throw new Error(`${detail} (${response.status})`)}const queued=await response.json();if(!queued.job_id)throw new Error('Backend did not return a job_id');for(let attempt=0;attempt<360;attempt++){await sleep(attempt===0?500:2000);let statusResponse;try{statusResponse=await fetch(`${API_BASE}/api/meetings/jobs/${encodeURIComponent(queued.job_id)}`)}catch(error){throw new Error('Lost connection to backend while polling processing status.')}if(!statusResponse.ok)throw new Error(`Processing status request failed (${statusResponse.status})`);const job=await statusResponse.json();if(job.status==='queued'||job.status==='processing'){setProcessingStage(job.status==='queued'?'stt':'tasks');continue}if(job.status==='failed')throw new Error(job.error||'Backend processing failed');if(job.status==='completed')return normalize(job.result);throw new Error(`Unknown backend job status: ${job.status||'missing'}`)}throw new Error('Processing timed out after 12 minutes')}
function show(id){['uploadView','processingView','resultView'].forEach(x=>$(x).hidden=x!==id)}
function start(file){$('processingFile').textContent=file?.name||'Meeting recording';$('processingHint').style.color='';show('processingView');setProcessingStage('stt');processMeeting(file).then(data=>{state.data=data;render();show('resultView');$('exportTopBtn').hidden=false;$('pageTitle').textContent='Review protocol'}).catch(error=>{console.error(error);showProcessingError(error.message||'Unable to process this recording')})}
function startDemo(){state.audioUrl=null;state.fileName='Sample meeting · local demo';state.data=clone(MOCK);render();show('resultView');$('exportTopBtn').hidden=false;$('pageTitle').textContent='Review protocol (demo)'}
function render(){const d=state.data,m=d.meeting,s=d.summary; $('meetingTitle').textContent=m.title||'Meeting protocol';$('meetingDate').textContent=m.date||'Date not set';$('meetingDuration').textContent=fmtTime(m.duration_seconds);$('meetingLanguage').textContent=m.language||'Language not set';$('summaryText').textContent=s.executive_summary||'';$('topicList').innerHTML=(s.key_topics||[]).map(x=>`<span class="topic">${esc(x)}</span>`).join('');$('decisionCount').textContent=(s.decisions||[]).length;$('taskCount').textContent=d.action_items.length;$('segmentCount').textContent=d.transcript.length;const avg=d.action_items.reduce((a,x)=>a+(Number(x.confidence)||0),0)/(d.action_items.length||1);$('confidenceValue').textContent=`${Math.round(avg*100)}%`;const decisionText=x=>typeof x==='string'?x:(x&& (x.decision||x.text||''));$('decisionList').innerHTML=(s.decisions||[]).map(x=>`<div class="decision">${esc(decisionText(x))}<div class="decision-meta"><span>Captured from protocol</span></div></div>`).join('');$('taskList').innerHTML=d.action_items.map((x,i)=>taskHtml(x,i)).join('');$('transcriptList').innerHTML=d.transcript.map((x,i)=>`<div class="transcript-line" data-start="${x.start}" data-index="${i}"><div class="timestamp">${fmtTime(x.start)}</div><div><div class="speaker">${esc(x.speaker||'SPEAKER')}</div><div class="transcript-text">${esc(x.text)}</div></div></div>`).join('');document.querySelectorAll('.transcript-line').forEach(x=>x.addEventListener('click',()=>seek(Number(x.dataset.start),x.dataset.index)));if(state.audioUrl)$('audioPlayer').src=state.audioUrl}
function taskHtml(x,i){return `<article class="task-card"><div class="task-header"><div class="task-title">${esc(x.task)}</div><span class="confidence">${Math.round((x.confidence||0)*100)}% confidence</span></div><div class="task-fields"><label class="field-chip editable"><b>ASSIGNEE</b><input data-field="assignee" data-index="${i}" value="${esc(x.assignee||'Not assigned')}" /></label><label class="field-chip editable"><b>DEADLINE</b><input data-field="deadline" data-index="${i}" value="${esc(x.deadline||'Not specified')}" /></label><span class="field-chip"><b>SPEAKER</b>${esc(x.speaker||'—')}</span></div><div class="task-footer"><div class="source-quote">“${esc(x.source_quote||x.task)}” · ${fmtTime(x.timestamp_start)}–${fmtTime(x.timestamp_end)}</div><button class="evidence-btn" data-evidence="${x.timestamp_start}" data-index="${i}">▶ Play evidence</button></div></article>`}
function seek(time,index){const p=$('audioPlayer');if(p.src){p.currentTime=time;p.play().catch(()=>{})}const segment=state.data.transcript.findIndex(x=>Number(x.start)<=time&&Number(x.end)>=time);const active=segment>=0?segment:index;$('nowPlaying').textContent=`Playing evidence at ${fmtTime(time)} — ${state.data.transcript[active]?.text||'source phrase'}`;document.querySelectorAll('.transcript-line').forEach(x=>x.classList.toggle('active',x.dataset.index==active))}
document.addEventListener('input',e=>{if(e.target.matches('input[data-field]'))state.data.action_items[Number(e.target.dataset.index)][e.target.dataset.field]=e.target.value});document.addEventListener('click',e=>{const b=e.target.closest('[data-evidence]');if(b)seek(Number(b.dataset.evidence),Number(b.dataset.index))});
function xml(s){return esc(s)}
function crc32(bytes){let table=crc32.table;if(!table){table=crc32.table=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}}let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
function u32(n){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}function cat(...arrs){const n=arrs.reduce((a,x)=>a+x.length,0),o=new Uint8Array(n);let p=0;arrs.forEach(x=>{o.set(x,p);p+=x.length});return o}
function zip(files){const enc=new TextEncoder(),local=[],central=[];let offset=0;files.forEach(([name,content])=>{const nb=enc.encode(name),data=enc.encode(content),crc=crc32(data),head=cat(new Uint8Array([80,75,3,4,20,0,0,0,0,0,0,0,0,0]),u32(crc),u32(data.length),u32(data.length),new Uint8Array([nb.length&255,nb.length>>>8,0,0]),nb,data);local.push(head);const ch=cat(new Uint8Array([80,75,1,2,20,0,20,0,0,0,0,0,0,0]),u32(crc),u32(data.length),u32(data.length),new Uint8Array([nb.length&255,nb.length>>>8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),nb);central.push(ch);offset+=head.length});let body=cat(...local),cd=cat(...central),eoc=cat(new Uint8Array([80,75,5,6,0,0,0,0,files.length&255,files.length>>>8,files.length&255,files.length>>>8,cd.length&255,cd.length>>>8,cd.length>>>16,cd.length>>>24,body.length&255,body.length>>>8,body.length>>>16,body.length>>>24,0,0,0,0]));return cat(body,cd,eoc)}
function paragraph(text,style='Normal'){return `<w:p><w:pPr><w:pStyle w:val="${style}"/></w:pPr><w:r><w:t xml:space="preserve">${xml(text)}</w:t></w:r></w:p>`}
function exportDocx(){const d=state.data,m=d.meeting,s=d.summary;let body=paragraph('ПРОТОКОЛ СОВЕЩАНИЯ','Title')+paragraph(m.title||'Совещание','Heading1')+paragraph(`Дата: ${m.date||'—'}    Длительность: ${fmtTime(m.duration_seconds)}    Язык: ${m.language||'—'}`)+paragraph('Саммари','Heading1')+paragraph(s.executive_summary||'');body+=paragraph('Ключевые темы','Heading1')+(s.key_topics||[]).map(x=>paragraph('• '+x)).join('')+paragraph('Решения','Heading1')+(s.decisions||[]).map(x=>paragraph('• '+x)).join('')+paragraph('Поручения','Heading1');d.action_items.forEach((x,i)=>{body+=paragraph(`${i+1}. ${x.task}`)+paragraph(`Ответственный: ${x.assignee||'—'} | Срок: ${x.deadline||'—'} | Уверенность: ${Math.round((x.confidence||0)*100)}%`)+paragraph(`Источник (${fmtTime(x.timestamp_start)}): ${x.source_quote||x.task}`)});body+=paragraph('Приложение: транскрипт','Heading1');d.transcript.forEach(x=>body+=paragraph(`[${fmtTime(x.start)}] ${x.speaker||'SPEAKER'}: ${x.text}`));const files=[['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>'],['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>'],['word/document.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr/></w:body></w:document>`]];const blob=new Blob([zip(files)],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='meeting-protocol.docx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('DOMContentLoaded',()=>{const input=$('audioInput');$('browseBtn').addEventListener('click',()=>input.click());input.addEventListener('change',e=>e.target.files[0]&&start(e.target.files[0]));$('demoBtn').addEventListener('click',startDemo);$('newMeetingBtn').addEventListener('click',()=>{show('uploadView');$('exportTopBtn').hidden=true;$('pageTitle').textContent='Upload a meeting'});['exportBtn','exportTopBtn'].forEach(id=>$(id).addEventListener('click',exportDocx));const dz=$('dropzone');['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('dragging')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('dragging')}));dz.addEventListener('drop',e=>e.dataTransfer.files[0]&&start(e.dataTransfer.files[0]))});
